### ISSUE TITLE
Question: potential error messages

### ISSUE THREAD

**Issue by JayBrown** [sindresorhus/macos-trash#12]
I am using your `trash` CLI in this set of tools: https://github.com/JayBrown/Trash-Tools

At some point (in the `trashes` tool) I'm parsing `trash` output for error strings. So far I've encountered "volume doesn't have a trash" and "no permissions to trash file".

It seems that these error message come directly from the macOS system. Do you know if there's an info document somewhere that lists all possible `stderr` messages of the system's move-to-trash routine?

**Comment by sindresorhus** [comment]
Apple, unfortunately, doesn't document the possible errors, so it could be many of the errors in https://developer.apple.com/documentation/foundation/cocoaerror

Just an educated guess, at least also these:
- https://developer.apple.com/documentation/foundation/cocoaerror/2506416-filelocking
- https://developer.apple.com/documentation/foundation/cocoaerror/2506440-filereadunknown
