### ISSUE TITLE
Put Back doesn't work on High Sierra

### ISSUE THREAD

**Issue by Cykelero** [sindresorhus/macos-trash#5]
Testing `trash` on macOS 10.13.3, the option to Put Back deleted files doesn't show up.

I reproduced by simply creating a file in my Downloads folder using `touch`, then deleting it with `trash`. “Put Back” doesn't appear as an option when right-clicking the file in the Trash.

I hope that's not a bug in the macOS API 😖

**Comment by sindresorhus** [comment]
Duplicate of #4

**Comment by Cykelero** [comment]
Oh, I thought that other issue only was for fails when trashing multiple files at once, sorry!
