### ISSUE TITLE
empty-trash and ls-trash

### ISSUE THREAD

**Issue by alexreg** [sindresorhus/macos-trash#9]
Thanks for creating this handy tool. Any chance of adding an `empty-trash` (Swift version) and `ls-trash` at some point? Or is the contents of the Trash always guaranteed to simply be the same as `ls -a ~/.Trash`?

**Comment by sindresorhus** [comment]
No plans to do it in Swift. I have a cross-platform package for it though: https://github.com/sindresorhus/empty-trash You could just borrow the JXA: https://github.com/sindresorhus/empty-trash/blob/df6a66d065364e8609c89c93f899ddc7fb6ce93f/index.js#L28-L34

No interest in `ls-trash`, but I think you could just list the directory contents.

**Comment by alexreg** [comment]
Yep, I noticed that one. Just curious, but what was the original motivation to make a Swift version? Performance, or simply an exercise of sorts?
